import { Observation } from "./observation.interface";
import { initialUser } from "../user/user.initial";
import { initialStation } from "../station/station.initial";

// new Date().getTime()          // Get the time (milliseconds since January 1, 1970)

export const initialObservation : Observation = {
    // coordinates: undefined,
    //SECTION 0
    mimi: undefined,
    mjmj: "XX", 
    ddddddd: '',
    a1: undefined,
    bw: undefined,
    nbnbnb: undefined,
    yy: undefined,
    gg: "",
    iw: undefined,
    iiiii: '',
    ii: '',
    iii: '',
    lalala: undefined,
    qc: undefined,
    lolololo: undefined,
    //SECTION 1
    ir: undefined,
    ix: undefined,
    h: undefined,
    vv: undefined,
    n: undefined,
    dd: undefined,
    ff: undefined,
    fff: undefined,
    sn1_1: undefined,
    ttt: undefined,
    sn2_1: undefined,
    tdtdtd: undefined,
    p0p0p0p0: undefined,
    pppp: undefined,
    a3: undefined,
    hhh: undefined,
    a: undefined,
    ppp: undefined,
    rrr: undefined,
    tr: undefined,
    ww: undefined,
    w1w2: undefined,
    // w1: undefined,
    // w2: undefined,
    wawa: undefined,
    wa1: undefined,
    wa2: undefined,
    nh: undefined,
    cl: undefined,
    cm: undefined,
    ch: undefined,
    gggg: undefined,
    //SECTION 2
    ds: undefined,
    vs: undefined,
    ss: undefined,
    twtwtw: undefined,
    pwapwa: undefined,
    hwahwa: undefined,
    pwpw: undefined,
    hwhw: undefined,
    dw1dw1: undefined,
    dw2dw2: undefined,
    pw1pw1: undefined,
    hw1hw1: undefined,
    pw2pw2: undefined,
    hw2hw2: undefined,
    is: undefined,
    eses: undefined,
    rs: undefined,
    hwahwahwa: undefined,
    sw: undefined,
    tbtbtb: undefined,
    ci: undefined,
    si: undefined,
    bi: undefined,
    di: undefined,
    zi: undefined,
    //SECTION 3
    sn1_3: undefined,
    txtxtx: undefined,
    sn2_3: undefined,
    tntntn: undefined,
    ind89: undefined,
    p24p24p24: undefined,
    //SECTION 5
    ichw: undefined,
    icm: undefined,
    cs: undefined,
    icf: undefined,
    icp: undefined,
    icq: undefined,

    dateObservation: new Date(),
    observerName: undefined,

    observer: undefined,
    station: undefined,
}